"use client";
import { useState } from "react";
import { CheckCircle2, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function ApplicationForm(){const [state,setState]=useState<"idle"|"sending"|"done"|"error">("idle"); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");const res=await fetch("/api/applications",{method:"POST",body:new FormData(e.currentTarget)});setState(res.ok?"done":"error")}
if(state==="done")return <section className="grid min-h-[32rem] place-items-center rounded-xl border bg-white p-10 text-center shadow-sm"><div><CheckCircle2 className="mx-auto size-14 text-[#e87b2f]"/><h2 className="mt-5 text-2xl font-bold">Application received</h2><p className="mt-3 max-w-md leading-7 text-slate-600">Thank you. Apex will review your information and contact you with the next step.</p></div></section>;
return <form onSubmit={submit} className="rounded-xl border bg-white p-6 shadow-sm md:p-9"><div className="grid gap-6 md:grid-cols-2"><Field label="Your name" name="contactName" required/><Field label="Company name" name="companyName" required/><Field label="Email" name="email" type="email" required/><Field label="Phone" name="phone" type="tel" required/><Field label="Website or LinkedIn" name="website"/><Field label="Primary markets / regions" name="markets" required/></div><div className="mt-6"><Label htmlFor="experience">Tell us about your fleet experience and professional network</Label><Textarea id="experience" name="experience" required rows={6} className="mt-2" placeholder="Industries, fleet types, decision-maker relationships, and the kinds of opportunities you expect to encounter…"/></div><div className="mt-6"><Label htmlFor="document">Supporting document <span className="font-normal text-slate-500">(optional)</span></Label><Input id="document" name="document" type="file" className="mt-2 h-auto py-2" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg"/><p className="mt-2 text-xs text-slate-500">Resume, capabilities overview, or other relevant reference.</p></div><label className="mt-6 flex gap-3 text-sm leading-6 text-slate-600"><input type="checkbox" name="attest" required className="mt-1 size-4 accent-[#e87b2f]"/>I confirm this information is accurate and understand that applying does not guarantee acceptance or compensation.</label>{state==="error"&&<p className="mt-4 text-sm font-semibold text-red-600">We couldn’t submit your application. Please try again.</p>}<Button disabled={state==="sending"} size="lg" className="mt-7 w-full bg-[#e87b2f] font-bold hover:bg-[#bc5a15]">{state==="sending"?<><Loader2 className="animate-spin"/>Submitting…</>:"Submit application"}</Button></form>}
function Field({label,name,type="text",required=false}:{label:string,name:string,type?:string,required?:boolean}){return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} className="mt-2"/></div>}
