"use client";
import { useState } from "react";
import { CheckCircle2, FileSignature } from "lucide-react";
import { AgreementTerms } from "@/components/agreement-terms";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type AgreementPartner = { agreementStatus:string; agreementVersion:string; agreementViewedAt:string|null; agreementSignedAt:string|null; signerName:string|null; contactName:string };
export function AgreementCard({partner,onSigned}:{partner:AgreementPartner;onSigned:()=>void}){const [open,setOpen]=useState(false),[name,setName]=useState(""),[consent,setConsent]=useState(false),[error,setError]=useState("");async function action(type:string){setError("");const run=()=>fetch("/api/agreement",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:type,signerName:name,consent})});let res=await run();if(res.status===401){await new Promise(r=>setTimeout(r,400));res=await run()}const body=await res.json();if(!res.ok)return setError(body.error||"Unable to update agreement");if(type==="sign"){setOpen(false);onSigned()}}function view(v:boolean){setOpen(v);if(v&&!partner.agreementViewedAt)action("view")}
if(partner.agreementStatus==="signed")return <section className="mt-8 rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex gap-3"><CheckCircle2 className="text-emerald-700"/><div><h2 className="font-bold text-emerald-950">Agreement signed</h2><p className="mt-1 text-sm text-emerald-900">Signed by {partner.signerName||partner.contactName}{partner.agreementSignedAt?` on ${new Date(partner.agreementSignedAt).toLocaleDateString()}`:""}. Your lead qualification card is unlocked.</p></div></div></section>;
if(partner.agreementStatus!=="sent"&&partner.agreementStatus!=="viewed")return null;
return <section className="mt-8 rounded-xl border border-orange-200 bg-orange-50 p-6"><div className="flex gap-4"><FileSignature className="mt-1 text-[#e87b2f]"/><div className="flex-1"><h2 className="font-bold text-[#0d1f35]">Referral Partner Agreement ready for review</h2><p className="mt-2 text-sm text-slate-700">Apex approved your application and issued agreement version {partner.agreementVersion}. Review the complete terms and sign electronically to activate your partner account.</p><Dialog open={open} onOpenChange={view}><DialogTrigger asChild><Button className="mt-4 bg-[#e87b2f] font-bold hover:bg-[#bc5a15]">Review and sign agreement</Button></DialogTrigger><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Review and sign</DialogTitle></DialogHeader><AgreementTerms/><div className="mt-6 rounded-lg border bg-slate-50 p-5"><Label htmlFor="signerName">Type your full legal name</Label><Input id="signerName" value={name} onChange={e=>setName(e.target.value)} className="mt-2"/><label className="mt-4 flex gap-3 text-sm leading-6"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 accent-[#e87b2f]"/>I have reviewed the complete agreement, agree to its terms, consent to electronic records and signatures, and intend my typed name to be my electronic signature.</label>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><Button disabled={!name.trim()||!consent} onClick={()=>action("sign")}>Sign and activate</Button><Button variant="outline" onClick={()=>action("decline")}>Decline agreement</Button></div></div></DialogContent></Dialog></div></div></section>}
