create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  email text not null,
  contact_name text not null,
  company_name text not null,
  phone text not null default '', website text not null default '', markets text not null default '', experience text not null default '',
  status text not null default 'application_received',
  agreement_status text not null default 'not_sent',
  agreement_version text not null default '2026-09-04',
  agreement_sent_at timestamptz, agreement_email_status text not null default 'not_sent', agreement_email_sent_at timestamptz,
  agreement_email_message_id text, agreement_email_error text, agreement_viewed_at timestamptz, agreement_signed_at timestamptz,
  agreement_declined_at timestamptz, signer_name text, signer_email text, signature_consent boolean not null default false,
  accepted_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists partners_email_idx on public.partners (lower(email));

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  partner_email text not null, company_name text not null, contact_name text not null, contact_email text not null, opportunity text not null,
  lead_path text not null default 'commercial_fleet', fleet_size integer not null default 0, fleet_count_source text not null default 'unverified',
  vehicle_types text not null default '', location text not null default '', service_location_type text not null default 'unknown',
  operating_hours text not null default '', need_type text not null default 'ongoing', maintenance_scope text not null default '',
  decision_maker text not null default '', decision_access text not null default 'unknown', current_vendor_status text not null default 'unknown',
  contract_end_date date, desired_start_date date, dsp_self_pay text not null default 'not_applicable', new_to_pipeline boolean not null default true,
  introduced_before_contact boolean not null default true, category text not null default 'tbd', qualification_score integer not null default 0,
  qualification_decision text not null default 'manual_review', qualification_reasons text not null default '[]', routing_status text not null default 'not_started',
  inactivity_date timestamptz, notes text not null default '', status text not null default 'submitted', estimated_value numeric(12,2) not null default 0,
  compensation numeric(12,2) not null default 0, paid_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists referrals_partner_email_idx on public.referrals (lower(partner_email));

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  partner_email text not null, file_name text not null, object_key text not null,
  kind text not null default 'supporting_document', status text not null default 'received', created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  type text not null, title text not null, message text not null, entity_type text not null,
  entity_id bigint not null, read_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists notifications_unread_idx on public.notifications (read_at, created_at desc);

alter table public.partners enable row level security;
alter table public.referrals enable row level security;
alter table public.documents enable row level security;
alter table public.notifications enable row level security;

insert into storage.buckets (id, name, public)
values ('partner-documents', 'partner-documents', false)
on conflict (id) do update set public = false;

-- No public table or storage policies are intentionally created. All data access
-- is performed by authenticated server routes after partner/admin authorization.
