import Link from "next/link";
import { BadgeDollarSign, CheckCircle2, ClipboardCheck, FileSignature, GitBranch, Handshake, Send, ShieldCheck } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { ReferenceLayout } from "@/components/reference-layout";
import { Button } from "@/components/ui/button";
import { PrintWorkflowButton } from "./print-workflow-button";

export const dynamic = "force-dynamic";

const stages = [
  { n:"01", title:"Partner application submitted", owner:"Applicant", icon:ClipboardCheck, status:"Application Received", details:"The applicant first verifies their email with a one-time code sent to that address, then submits contact information, company details, markets, fleet experience, professional-network information, attestations, and any supporting document.", system:"Requires a verified, deliverable email before any application data is saved, then creates the partner record, timestamps the submission, stores uploaded documents, and creates an unread admin notification.", exit:"Apex begins its review or declines the application." },
  { n:"02", title:"Application reviewed", owner:"Apex", icon:ShieldCheck, status:"Under Review", details:"Apex checks the applicant’s identity, experience, network relevance, professionalism, potential conflicts, and ability to make credible fleet introductions.", system:"The admin records the review status. The applicant can see that the application is being reviewed but cannot submit referrals.", exit:"Apex selects Approved or Declined. A decline ends the onboarding workflow." },
  { n:"03", title:"Application approved", owner:"Apex + system", icon:CheckCircle2, status:"Approved / Agreement Sent", details:"Approval authorizes agreement review; it does not yet activate the applicant as a referral partner.", system:"Issues the current agreement in the portal, records the agreement version and issued timestamp, emails access instructions, tracks email delivery, and alerts Apex if delivery fails.", exit:"The applicant opens the agreement." },
  { n:"04", title:"Agreement reviewed and signed", owner:"Applicant", icon:FileSignature, status:"Agreement Viewed → Agreement Signed", details:"The applicant reviews the complete Referral Partner Agreement, enters their legal name, consents to electronic records and signatures, and signs or declines.", system:"Captures issued, viewed, signed, or declined timestamps; agreement version; authenticated email; signer name; consent; and acceptance date. Each action creates an admin notification.", exit:"A signed agreement activates the partner and unlocks referral submission. A decline stops the process." },
  { n:"05", title:"Referral submitted", owner:"Partner", icon:Send, status:"Submitted", details:"The active partner completes the Lead Qualification Card with objective fleet, location, service, decision-maker, timing, vendor, and contact information. Fleet facts use structured selections — a vehicle-count range, vehicle class, maintenance scope, and business need — rather than free text, so intake data stays consistent. Amazon DSP submissions must confirm self-pay.", system:"Creates the referral record, timestamps it, calculates a preliminary qualification score, assigns an initial decision, sets the 12-month inactivity date, and sends Apex an unread notification.", exit:"The referral enters qualification review." },
  { n:"06", title:"Eligibility and qualification confirmed", owner:"Apex", icon:ClipboardCheck, status:"Under Review → Qualified", details:"Apex validates the submitted facts and confirms the company is new to the pipeline, the referral was submitted before Apex contact, the partner can facilitate the introduction, and the opportunity is commercially viable.", system:"Preserves the automated score and reasons while allowing Apex to record the operational decision. Duplicate, ineligible, or weak opportunities move to Not Moving Forward; uncertain opportunities remain in manual review.", exit:"Eligible opportunities move to confidential routing review." },
  { n:"07", title:"Opportunity routed", owner:"Apex", icon:GitBranch, status:"Routing Review → Pursuing", details:"Every eligible referral is automatically flagged Needs Routing Review the moment it is submitted, and stays flagged until a routing decision is recorded. Apex applies the internal five-gate routing analysis to determine whether the opportunity is pursued as an Apex-direct engagement, routed through a provider such as SVT, or handled as a custom enterprise opportunity.", system:"The admin view surfaces the objective facts the routing gates depend on — fleet size, vehicle class, location, maintenance scope, and business need — alongside a short rationale field so the routing decision is logged at the moment it is made. The partner sees the customer-facing opportunity status and compensation category, but the routing rationale, provider economics, and internal analysis remain owner-only.", exit:"Apex accepts the opportunity for pursuit or closes it as Not Moving Forward." },
  { n:"08", title:"Opportunity developed", owner:"Apex", icon:Handshake, status:"Pursuing → Proposal → Won", details:"Apex or the selected provider completes discovery, confirms scope, develops pricing, issues a proposal, and manages the sales process. The partner’s role remains limited to the introduction unless Apex authorizes more in writing.", system:"The admin updates milestones so the partner can track progress without needing confidential pricing, margin, or provider information.", exit:"The opportunity is won, lost, declined, or becomes inactive." },
  { n:"09", title:"Compensation eligibility triggered", owner:"Apex", icon:BadgeDollarSign, status:"Commission Pending", details:"A referral fee is earned only when all agreement requirements are satisfied and the triggering business event occurs. An introduction alone never creates a payment obligation.", system:"Apex confirms the compensation category, qualifying amount, trigger date, exceptions, and supporting revenue or engagement evidence before approving payout.", exit:"The payment trigger is verified and the amount is approved." },
  { n:"10", title:"Commission approved and paid", owner:"Apex", icon:BadgeDollarSign, status:"Approved for Payout → Paid", details:"Apex records the final amount and pays the partner according to the agreement. Apex-direct fees are due within 10 business days after the engagement is confirmed and active. Partner-routed and custom fees are due within 10 business days after Apex or Brooke receives the qualifying payment; installment receipts are paid proportionally.", system:"Records compensation amount, payment status, paid date, and the final audit trail. The paid amount remains visible in the partner’s referral history.", exit:"The payout is reconciled and the referral is closed, or remains open for an eligible installment balance." },
];

export default async function PartnerWorkflow(){await requireAdmin();return <ReferenceLayout eyebrow="Admin-only operating procedure" title="Partner Application-to-Payout Workflow" subtitle="Confidential internal sequence for onboarding referral partners, qualifying opportunities, routing leads, and paying eligible compensation.">
  <div className="not-prose mb-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-orange-200 bg-orange-50 p-4 print:hidden"><p className="text-sm font-semibold text-slate-700">Visible only to authorized Apex administrators.</p><PrintWorkflowButton /></div>
  <div className="not-prose rounded-xl bg-[#0d1f35] p-6 text-white"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#f39a5b]">Governing principle</p><p className="mt-3 text-lg leading-8 text-slate-100">A partner becomes active only after approval and signature. A referral becomes payable only after it is eligible, actively pursued, converted, and the applicable payment trigger in the agreement has occurred.</p></div>
  <h2>Roles and control</h2><div className="not-prose grid gap-4 md:grid-cols-3"><Role title="Partner" text="Provides accurate information, makes the introduction, monitors status, and keeps payment details current."/><Role title="Apex" text="Owns approval, qualification, routing, pursuit, compensation classification, payout approval, and exceptions."/><Role title="Portal" text="Enforces access, timestamps actions, creates alerts, calculates preliminary qualification, and preserves the audit trail."/></div>
  <h2>End-to-end workflow</h2><div className="not-prose space-y-5">{stages.map(stage=>{const Icon=stage.icon;return <section key={stage.n} className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-[#fff0e5] text-[#e87b2f]"><Icon className="size-5"/></span><div><p className="text-xs font-black tracking-[.16em] text-slate-400">STAGE {stage.n}</p><h3 className="mt-1 text-lg font-bold text-slate-950">{stage.title}</h3><p className="mt-1 text-sm text-slate-500">Owner: {stage.owner}</p></div></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">{stage.status}</span></div><div className="mt-5 grid gap-4 text-sm leading-6 text-slate-600 md:grid-cols-3"><Detail label="Required activity" text={stage.details}/><Detail label="Portal and record" text={stage.system}/><Detail label="Exit condition" text={stage.exit}/></div></section>})}</div>
  <h2>Compensation rules</h2><div className="not-prose overflow-x-auto rounded-2xl border"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Category</th><th className="p-4">Amount</th><th className="p-4">Payment trigger</th><th className="p-4">Timing</th></tr></thead><tbody className="divide-y"><PayRow category="Apex direct — small project" amount="$500" trigger="Engagement confirmed and active" timing="Within 10 business days"/><PayRow category="Apex direct — ongoing consulting" amount="$1,500" trigger="Engagement confirmed and active" timing="Within 10 business days"/><PayRow category="Apex direct — larger or multi-site" amount="$3,000" trigger="Engagement confirmed and active" timing="Within 10 business days"/><PayRow category="Apex direct — major enterprise" amount="$5,000" trigger="Engagement confirmed and active" timing="Within 10 business days"/><PayRow category="Partner-routed" amount="25% of qualifying compensation" trigger="Apex or Brooke receives qualifying payment" timing="Within 10 business days of receipt; proportional for installments"/><PayRow category="Custom / enterprise" amount="Written opportunity-specific fee" trigger="The written trigger and qualifying payment occur" timing="Per written terms; otherwise within 10 business days of receipt"/></tbody></table></div>
  <h2>Exception and closure rules</h2><ul><li><b>Declined applicant:</b> onboarding ends; no agreement or referral access is issued.</li><li><b>Agreement declined:</b> the applicant is not activated and cannot submit referrals.</li><li><b>Duplicate or pre-existing opportunity:</b> not eligible for referral compensation.</li><li><b>Introduction after Apex contact:</b> not eligible unless Apex approves an exception in writing.</li><li><b>Not moving forward:</b> opportunity closes without payment unless later reopened and approved.</li><li><b>Inactive:</b> a referral not active and engaged within 12 months expires unless Apex extends it in writing.</li><li><b>Won but unpaid:</b> partner-routed or custom compensation remains pending until Apex or Brooke receives the qualifying payment.</li><li><b>Installments:</b> eligible partner-routed compensation is paid proportionally as qualifying payments are received.</li><li><b>Dispute or correction:</b> Apex documents the issue, supporting records, decision, and any adjustment in the referral record.</li></ul>
  <h2>Minimum audit record</h2><p>Every completed workflow should retain:</p><ul><li>Application information, supporting documents, status history, reviewer, and decision date.</li><li>Agreement version, delivery status, issued/viewed/signed timestamps, signer identity, and consent.</li><li>Original referral facts, qualification score and reasons, eligibility checks, introduction evidence, and inactivity date.</li><li>Routing decision and rationale, opportunity milestones, compensation category, payment trigger, calculation, approval, and exceptions.</li><li>Payment amount, date, method or reference, remaining eligible balance, and final closeout status.</li></ul>
  <div className="not-prose mt-8 flex flex-wrap gap-3 border-t pt-6 print:hidden"><Button asChild variant="outline"><Link href="/admin">Back to administration</Link></Button><Button asChild variant="outline"><Link href="/resources/agreement">View governing agreement</Link></Button><PrintWorkflowButton /></div><p className="mt-8 text-sm text-slate-500">Operational workflow version 2026-09-10. If this procedure conflicts with the signed Referral Partner Agreement, the signed agreement controls.</p>
</ReferenceLayout>}

function Role({title,text}:{title:string;text:string}){return <div className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function Detail({label,text}:{label:string;text:string}){return <div><p className="font-bold text-slate-900">{label}</p><p className="mt-1">{text}</p></div>}
function PayRow({category,amount,trigger,timing}:{category:string;amount:string;trigger:string;timing:string}){return <tr><td className="p-4 font-semibold text-slate-900">{category}</td><td className="p-4">{amount}</td><td className="p-4">{trigger}</td><td className="p-4">{timing}</td></tr>}
